### ISSUE TITLE
Parallel 2D geometry wrong when detector is not centered

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#687] opened 2016-10-26 13:54 UTC
There is an obvious bug in (at least) the definition of the 2D parallel geometry coupling to ASTRA. Examples work for centered detectors, but when defining a detector not centered around 0, results are wrong.

I wouldn't be surprised about similar bugs in other geometries.

**Comment by adler-j** [comment] 2016-10-26 14:13
Duplicate of #359. Closing.

Also see astra [PR #69](https://github.com/astra-toolbox/astra-toolbox/pull/69) which, when added, should solve this.

**Closed by adler-j** 2016-10-26 14:13 UTC
Labels: bug, odl tomo

**Comment by kohr-h** [comment] 2016-10-26 14:54
Oh, it's that old. And not on our side... Okay, I'll just wait then :-)
