### ISSUE TITLE
Fourier transform problem appeared in 3D reconstruction using LDDMM method?

### ISSUE THREAD

**Issue by chongchenmath** [odlgroup/odl#941] opened 2017-02-24 14:31 UTC
When testing 2D reconstruction with LDDMM method, it works well even if I have the following warning:
```
/home/chchen/odl/odl/trafos/util/ft_utils.py:337: ComplexWarning: Casting complex values to real discards the imaginary part
```

But for 3D reconstruction with the same method, it doesn't work with the following error: 

```
runfile('/home/chchen/odl/odl/deform/LDDMM_gradiant_descent_scheme.py', wdir='/home/chchen/odl/odl/deform')
/home/chchen/miniconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)
geom
/home/chchen/odl/odl/trafos/util/ft_utils.py:337: ComplexWarning: Casting complex values to real discards the imaginary part
  out[:] = arr
Traceback (most recent call last):

  File "<ipython-input-1-42b50ed24e41>", line 1, in <module>
    runfile('/home/chchen/odl/odl/deform/LDDMM_gradiant_descent_scheme.py', wdir='/home/chchen/odl/odl/deform')

  File "/home/chchen/miniconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/home/chchen/miniconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/chchen/odl/odl/deform/LDDMM_gradiant_descent_scheme.py", line 514, in <module>
    gradS, template, time_itvs, niter, eps, lamb, kernel, impl, callback)

  File "/home/chchen/odl/odl/deform/LDDMM_gradiant_descent_scheme.py", line 335, in LDDMM_gradient_descent_solver
    vectorial_ft_fit_op(tmp) * ft_kernel_fitting)

  File "/home/chchen/odl/odl/operator/operator.py", line 693, in __call__
    out = self._call_out_of_place(x, **kwargs)

  File "/home/chchen/odl/odl/operator/pspace_ops.py", line 232, in _call
    out[i] += op(x[j])

  File "/home/chchen/odl/odl/operator/operator.py", line 693, in __call__
    out = self._call_out_of_place(x, **kwargs)

  File "/home/chchen/odl/odl/operator/operator.py", line 1310, in _call
    return self.left(self.right(x))

  File "/home/chchen/odl/odl/operator/operator.py", line 693, in __call__
    out = self._call_out_of_place(x, **kwargs)

  File "/home/chchen/odl/odl/operator/operator.py", line 62, in _default_call_out_of_place
    op._call_in_place(x, out, **kwargs)

  File "/home/chchen/odl/odl/trafos/fourier.py", line 890, in _call
    out[:] = self._call_pyfftw(x.asarray(), out.asarray(), **kwargs)

  File "/home/chchen/odl/odl/trafos/fourier.py", line 1623, in _call_pyfftw
    self._postprocess(fft_arr, out=out)

  File "/home/chchen/odl/odl/trafos/fourier.py", line 1515, in _postprocess
    x, shift=self.shifts, axes=self.axes, sign=self.sign, out=out)

  File "/home/chchen/odl/odl/trafos/util/ft_utils.py", line 364, in dft_preprocess_data
    onedim_arrs.append(_onedim_arr(length, shift))

  File "/home/chchen/odl/odl/trafos/util/ft_utils.py", line 357, in _onedim_arr
    factor *= -imag * np.pi * (1 - 1.0 / length)

TypeError: Cannot cast ufunc multiply output from dtype('complex64') to dtype('float32') with casting rule 'same_kind'
```

Do you have some suggestions?

**Comment by adler-j** [comment] 2017-02-24 14:44
We need a MWE that causes this problem. Please provide a code example.

Further, this is pseudo-duplicated of #919.

**Comment by chongchenmath** [comment] 2017-02-24 15:29
MWE:

```python
import numpy as np
from odl.trafos import FourierTransform
from odl.discr import uniform_discr


def kernel(x):
    sigma = 2.0
    scaled = [xi ** 2 / (2 * sigma ** 2) for xi in x]
    return np.exp(-sum(scaled))


# --- 3D test for Fourier transform --- #   


space_3d = uniform_discr([-90.5, -90.5, -90.5], [90.5, 90.5, 90.5],
                         (181, 181, 181), interp='linear', dtype='float32')

kernel_func_3d = space_3d.element(kernel)


shifts = [not s % 2 for s in space_3d.shape]
ft_op_3d = FourierTransform(space_3d, halfcomplex=False,
                            shift=shifts, impl='pyfftw')

result = (2 * np.pi) ** (space_3d.ndim / 2.0) * ft_op_3d.inverse(
        ft_op_3d(kernel_func_3d) * ft_op_3d(kernel_func_3d))
    

# --- 2D test for Fourier transform --- #   


space_2d = uniform_discr([-90.5, -90.5], [90.5, 90.5],
                         (181, 181), interp='linear', dtype='float32')

kernel_func_2d = space_2d.element(kernel)


shifts = [not s % 2 for s in space_2d.shape]
ft_op_2d = FourierTransform(space_2d, halfcomplex=False,
                            shift=shifts, impl='pyfftw')

result = (2 * np.pi) ** (space_2d.ndim / 2.0) * ft_op_2d.inverse(
        ft_op_2d(kernel_func_2d) * ft_op_2d(kernel_func_2d))
```

Seems neither 2D nor 3D above works.

**Comment by adler-j** [comment] 2017-02-24 15:31
Ok, then this is a duplicate of #919, closing. Continue discussion in that issue, @kohr-h is supposedly on it.

**Closed by adler-j** 2017-02-24 15:31 UTC
Labels: bug, discussion, help wanted
