### ISSUE TITLE
Add indexing of tomographic geometries

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#1013] opened 2017-05-30 02:26 UTC
In order to do things such as #985, it would be great to be able to index geometries to obtain "sub-geometries". We did have a branch on this somewhere, but it was never finalized. Perhaps we can re-vitalize it?

**Comment by kohr-h** [comment] 2017-05-31 17:35
Duplicate of #434

**Closed** 2017-09-12 07:36 UTC
Labels: new feature, odl tomo

**Comment by mehrhardt** [comment] 2017-10-17 10:44
I am sorry to say, but it seems this issue is not really solved. Here are two examples that reveal a problem. I don't know what exact numbers the output should be, but in each of the two examples I expect all norms to be similar.

```
import odl
space = odl.uniform_discr(min_pt=[-20, -20], max_pt=[20, 20], shape=[40, 40], 
                          dtype='float32')

geometry = odl.tomo.parallel_beam_geometry(
        space, num_angles=20, det_shape=40)

G = odl.BroadcastOperator(
        *[odl.tomo.RayTransform(space, geometry[i::geometry.angles.size],
                                impl='astra_cpu')
          for i in range(geometry.angles.size)])

norms = [Gi.norm(estimate=True) for Gi in G]

norms
Out[7]: 
[13.199381750251304,
 12.8617218582955,
 12.729895205130077,
 12.871868456389452,
 13.229355185459603,
 12.809279320818561,
 11.681028481756286,
 10.818330989593109,
 10.221460572031081,
 9.7889233797725979,
 9.3333727517885041,
 8.8520438727503858,
 8.4865958045384353,
 8.2597344506830712,
 8.1012974017922073,
 7.3954396604256125,
 6.2437728377374189,
 5.196958077615986,
 4.1728932713147815,
 2.9514715823886819]
```

```
import odl
space = odl.uniform_discr(min_pt=[-20, -20], max_pt=[20, 20], shape=[40, 40], 
                          dtype='float32')

geometry = odl.tomo.parallel_beam_geometry(
        space, num_angles=20, det_shape=40)

G = odl.BroadcastOperator(
        *[odl.tomo.RayTransform(space, geometry[i::geometry.angles.size],
                                impl='astra_cpu')
          for i in range(geometry.angles.size)])

Gfull = odl.tomo.RayTransform(space, geometry, impl='astra_cpu')

norm = G.norm(estimate=True)
norm_full = Gfull.norm(estimate=True)

norm
Out[9]: 36.44940441257237

norm_full
Out[10]: 11.140616097252755
```

**Comment by adler-j** [comment] 2017-10-17 11:09
This does not look like an ODL bug to me, but it is instead a slight error on your end. Specifically, if we run this:

```python
import odl
space = odl.uniform_discr(min_pt=[-20, -20], max_pt=[20, 20], shape=[40, 40], 
                          dtype='float32')

geometry = odl.tomo.parallel_beam_geometry(
        space, num_angles=20, det_shape=40)

geometries = [geometry[i::geometry.angles.size]
              for i in range(geometry.angles.size)]
                  
                  
for geometry in geometries:
    print(geometry.motion_partition)
```

we get

```
uniform_partition(0.0, 3.14159265359, 1)
uniform_partition(0.157079632679, 3.14159265359, 1)
uniform_partition(0.314159265359, 3.14159265359, 1)
uniform_partition(0.471238898038, 3.14159265359, 1)
uniform_partition(0.628318530718, 3.14159265359, 1)
uniform_partition(0.785398163397, 3.14159265359, 1)
uniform_partition(0.942477796077, 3.14159265359, 1)
uniform_partition(1.09955742876, 3.14159265359, 1)
uniform_partition(1.25663706144, 3.14159265359, 1)
uniform_partition(1.41371669412, 3.14159265359, 1)
uniform_partition(1.57079632679, 3.14159265359, 1)
uniform_partition(1.72787595947, 3.14159265359, 1)
uniform_partition(1.88495559215, 3.14159265359, 1)
uniform_partition(2.04203522483, 3.14159265359, 1)
uniform_partition(2.19911485751, 3.14159265359, 1)
uniform_partition(2.35619449019, 3.14159265359, 1)
uniform_partition(2.51327412287, 3.14159265359, 1)
uniform_partition(2.67035375555, 3.14159265359, 1)
uniform_partition(2.82743338823, 3.14159265359, 1)
uniform_partition(2.98451302091, 3.14159265359, 1)
```

Notice that the upper end of the angular interval does not increase, while the lower end does increase? Also note that there is only one angle per interval.

This is because you use this syntax: `geometry[i::geometry.angles.size]`, which should be read: "Take the subinterval from i, to the end, with step length `geometry.angles.size`", now since the step length is the same as the number of elements, this means that the result will have only one element. On the other hand, you slowly increase the minimum point, so it changes, but since you ask for "to the end", the final point does not change.

This is validated since we see that the operator norm does scales as the square root of the angular interval, and your norm results can be reproduced basically exactly:

```
for geometry in geometries:
    print(7.45 * geometry.motion_partition.extent ** 0.5)
[ 13.20478119]
[ 12.87042866]
[ 12.52715537]
[ 12.17420672]
[ 11.81071535]
[ 11.43567596]
[ 11.04791258]
[ 10.64603495]
[ 10.22837953]
[ 9.79292783]
[ 9.33719032]
[ 8.85803651]
[ 8.35143691]
[ 7.8120539]
[ 7.23255652]
[ 6.60239059]
[ 5.90535767]
[ 5.11418976]
[ 4.17571846]
[ 2.95267884]
```

Anyway, the solution for you is to simply use `geometry[i]` instead of `geometry[i::geometry.angles.size]`. This gives a good result. Do note that it is not exactly constant, but this is expected since the domain is a square and not a circle.

**Comment by mehrhardt** [comment] 2017-10-17 11:23
Great, that all makes perfect sense.

We then should probably change the Kaczmarz example where I took this notation from

```
    n = 20

    ray_trafos = [odl.tomo.RayTransform(space, geometry[i::n])
                  for i in range(n)]
```

Although there the underlying spaces are not important (hence the example works fine), it would be better and cleaner the way you just wrote.

**Comment by adler-j** [comment] 2017-10-17 11:45
I agree, the current implementation is straight wrong, since what we get is something like

```
|1  1  1  |
 |2  2  2 |
  |3  3  3|
```

I guess the correct code would be

```
geometry[i:-n+i:n]
```

**Comment by mehrhardt** [comment] 2017-10-17 12:10
Not sure what is the "correct" way of using this geometry syntax but slicing 20 angles into 5 subsets should give you 4 angles per subset.

```
import odl
space = odl.uniform_discr(min_pt=[-20, -20], max_pt=[20, 20], shape=[40, 40], 
                          dtype='float32')

geometry = odl.tomo.parallel_beam_geometry(
        space, num_angles=20, det_shape=40)

n = 5
geometries2 = [geometry[i:-n+i:n] for i in range(n)]
geometries3 = [geometry[i::n] for i in range(n)]
```

```
geometries2[0].angles = array([ 0.07853982,  0.86393798,  1.64933614])
geometries3[0].angles = array([ 0.07853982,  0.86393798,  1.64933614,  2.43473431])
```
