### ISSUE TITLE
Kullback Leibler divergence misdefined

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#1039] opened 2017-06-21 09:13 UTC
In the definition of the KL divergence, it is customary (at least in PET imaging) that 0 log 0 := 0 and NOT 0 log 0 := inf which is implicitly used in ODL, see implementation below.
```
    # TODO: update when integration operator is in place: issue #440
    def _call(self, x):
        """Return the KL-diveregnce in the point ``x``.

        If any components of ``x`` is non-positive, the value is positive
        infinity.
        """
        if self.prior is None:
            tmp = ((x - 1 - np.log(x)).inner(self.domain.one()))
        else:
            tmp = ((x - self.prior + self.prior * np.log(self.prior / x))
                   .inner(self.domain.one()))
        if np.isnan(tmp):
            # In this case, some element was less than or equal to zero
            return np.inf
        else:
            return tmp
```
It is easy to fix this, if one finds all the indices where self.prior (I also find this naming of the variable misleading) is zero. However, this may be costly and to be avoided. Do you know any other smart solution for this?

**Comment by kohr-h** [comment] 2017-06-21 12:19
Valid point. Regarding the name `prior`, that may be something used in a statistical context, but in inverse problems it's clearly confusing. It's supposed to be a `target` distribution, isn't it?

Considering the current implementation, I think the check for zeros can be added without making the code much slower, if a the same time the code is optimized for in-place arithmetic. Here are some speed tests (this is slapped together and not checked for correctness):
```python
>>> def kl_simple(x, y):
...     # This code does:
...     # a1 = x - y  -> copy
...     # z1 = y / x -> copy
...     # z2 = log(z1)  -> copy
...     # z3 = y * z2  -> copy
...     # result = a1 + z3  -> copy
...     return x - y + y * np.log(y / x)
>>>
>>> def kl_optim(x, y):
...     tmp = y / x  # only copy here
...     np.log(tmp, out=tmp)
...     tmp -= 1
...     tmp *= y
...     tmp += x
...     return tmp
>>>
>>> def kl_optim_with_check(x, y):
...     cond = (y != 0)
...     tmp = y / x
...     tmp[cond] = np.log(tmp[cond])   # extra copy and indexing with array -> expensive
...     tmp -= 1
...     tmp *= y
...     tmp += x
...     return tmp
>>>
>>> # This is the worst case since the condition is `True` everywhere
>>> x = np.ones(int(1e8))
>>> y = x.copy()
>>>
>>> %timeit kl_simple(x, y)
1.4 s ± 34.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
>>> %timeit kl_optim(x, y)
843 ms ± 226 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
>>> %timeit kl_optim_with_check(x, y)
1.45 s ± 522 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
So the optimized version with check is roughly as fast as the original version without check.

The individual contributions:
```python
>>> # Negligible
>>> %timeit (x != 0)    
56.8 ms ± 59.6 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

>>> # Significant
>>> %timeit x[cond] = np.log(y[cond])
933 ms ± 3.65 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
>>> # Comparison with log on whole array
>>> %timeit np.log(x)
527 ms ± 449 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

My conclusion (assuming the optimized version is correct) is that with optimization, the added check is acceptable. While at it, the default case can also avoid one copy.

Would you do it @MatthiasJE?

**Comment by MatthiasJE** [comment] 2017-06-22 13:21
I gave it a try, @kohr-h, but struggled along the way, see PR #1040. Some indexing issue made Travis' check fail. As the tests with Travis take quite long, I tried to run the tests offline but could not make it to work to run in reasonable time either. Is there a way of just running tests on a particular file that I have been changing? Moreover, some of my changes (like renaming "prior" to "target") caused errors in many other files, thus I decided to undo them. Maybe it is better to first agree on a good solution for these names. In particular, I am not sure that I am happy with the name "target" either. In a PET context, the target would be the measured data but this may be different in other applications?

**Comment by kohr-h** [comment] 2017-06-22 15:50
> I gave it a try, @kohr-h, but struggled along the way, see PR #1040.

Very much appreciated.


> Is there a way of just running tests on a particular file that I have been changing?

Yes, you can do `pytest path/to/test/file.py` to just run a specific file in the test suite.


> Moreover, some of my changes (like renaming "prior" to "target") caused errors in many other files, thus I decided to undo them. Maybe it is better to first agree on a good solution for these names.


Sure. Related to renaming things, the "Find in files" tool of Spyder is quite handy for that. You can search for text (e.g. `prior=`) and you get clickable references to the found locations.

> In particular, I am not sure that I am happy with the name "target" either. In a PET context, the target would be the measured data but this may be different in other applications?


Nah, that was just a random thing that popped out of my mind. To my understanding, KL as we used it here measures the deviation of a stochastic process from another. If that other process is fixed, how should it be called? Of course, in the context of imaging, that's most likely the measured data, but it could also be something else which would be misnamed by the imaging nomenclature.
So I don't have a good answer to that, maybe @aringh or @ozanoktem can comment?

**Comment by MatthiasJE** [comment] 2017-06-22 16:55
>     Is there a way of just running tests on a particular file that I have been changing?
> 
> Yes, you can do pytest path/to/test/file.py to just run a specific file in the test suite.

Executing `pytest odl/solvers/functional/default_functionals.py` in a terminal causes the error: 
> NameError: name 'odl' is not defined
What am I doing wrong?

**Comment by adler-j** [comment] 2017-06-22 23:10
> What am I doing wrong?

You need to execute this from the ODL root folder, are you doing that?

I get

```
D:\Programming\ODL> pytest odl/solvers/functional/default_functionals.py
============================= test session starts =============================
platform win32 -- Python 2.7.12, pytest-3.0.3, py-1.4.30, pluggy-0.4.0
rootdir: D:\Programming\ODL\odl, inifile: pytest.ini
plugins: odl-0.5.4.dev0, pep8-1.0.6, cov-2.2.0
collected 11 items

odl\solvers\functional\default_functionals.py ...........

================ 11 passed, 1 pytest-warnings in 0.08 seconds =================
```

**Comment by MatthiasJE** [comment] 2017-06-23 08:44
Quick update:
- Yes, I did run it from the root directory
- I did not know that I have to install ODL. However, ever after installing it, the same error message appears.
- I do have pytest installed. The entire screen output reads as below.
- Can I verify the installation somehow? Maybe some paths are not set correctly?

> ehrhardt@TPX1:~/repositories/git_ODL/odl$ pytest solvers/functional/default_functionals.py 
> ============================= test session starts ==============================
> platform linux -- Python 3.5.2, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
> rootdir: /home/ehrhardt/repositories/git_ODL/odl, inifile: pytest.ini
> plugins: pep8-1.0.6
> collected 11 items 
> 
> solvers/functional/default_functionals.py FFFFFFFF.FF
> 
> =================================== FAILURES ===================================
> __ [doctest] odl.solvers.functional.default_functionals.GroupL1Norm.__init__ ___
> 216             power space.
> 217         exponent : non-zero float, optional
> 218             Exponent of the norm in each point. Values between
> 219             0 and 1 are currently not supported due to numerical
> 220             instability. Infinity gives the supremum norm.
> 221             Default: ``vfspace.exponent``, usually 2.
> 222 
> 223         Examples
> 224         --------
> 225         >>> space = odl.rn(2)
> UNEXPECTED EXCEPTION: NameError("name 'odl' is not defined",)
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.5/doctest.py", line 1321, in __run
>     compileflags, 1), test.globs)
> 
>   File "<doctest odl.solvers.functional.default_functionals.GroupL1Norm.__init__[0]>", line 1, in <module>
> 
> NameError: name 'odl' is not defined
> 
> /home/ehrhardt/repositories/git_ODL/odl/solvers/functional/default_functionals.py:225: UnexpectedException
> __ [doctest] odl.solvers.functional.default_functionals.IndicatorBox.__init__ __
> 831         lower : ``space.field`` element or ``space`` `element-like`, optional
> 832             The lower bound.
> 833             Default: ``None``, interpreted as -infinity
> 834         upper : ``space.field`` element or ``space`` `element-like`, optional
> 835             The upper bound.
> 836             Default: ``None``, interpreted as +infinity
> 837 
> 838         Examples
> 839         --------
> 840         >>> space = odl.rn(3)
> UNEXPECTED EXCEPTION: NameError("name 'odl' is not defined",)
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.5/doctest.py", line 1321, in __run
>     compileflags, 1), test.globs)
> 
>   File "<doctest odl.solvers.functional.default_functionals.IndicatorBox.__init__[0]>", line 1, in <module>
> 
> NameError: name 'odl' is not defined
> 
> /home/ehrhardt/repositories/git_ODL/odl/solvers/functional/default_functionals.py:840: UnexpectedException
>  [doctest] odl.solvers.functional.default_functionals.IndicatorGroupL1UnitBall.__init__ 
> 353             power space.
> 354         exponent : non-zero float, optional
> 355             Exponent of the norm in each point. Values between
> 356             0 and 1 are currently not supported due to numerical
> 357             instability. Infinity gives the supremum norm.
> 358             Default: ``vfspace.exponent``, usually 2.
> 359 
> 360         Examples
> 361         --------
> 362         >>> space = odl.rn(2)
> UNEXPECTED EXCEPTION: NameError("name 'odl' is not defined",)
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.5/doctest.py", line 1321, in __run
>     compileflags, 1), test.globs)
> 
>   File "<doctest odl.solvers.functional.default_functionals.IndicatorGroupL1UnitBall.__init__[0]>", line 1, in <module>
> 
> NameError: name 'odl' is not defined
> 
> /home/ehrhardt/repositories/git_ODL/odl/solvers/functional/default_functionals.py:362: UnexpectedException
>  [doctest] odl.solvers.functional.default_functionals.IndicatorNonnegativity.__init__ 
> 896 Initialize an instance.
> 897 
> 898         Parameters
> 899         ----------
> 900         space : `LinearSpace`
> 901             Domain of the functional.
> 902 
> 903         Examples
> 904         --------
> 905         >>> space = odl.rn(3)
> UNEXPECTED EXCEPTION: NameError("name 'odl' is not defined",)
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.5/doctest.py", line 1321, in __run
>     compileflags, 1), test.globs)
> 
>   File "<doctest odl.solvers.functional.default_functionals.IndicatorNonnegativity.__init__[0]>", line 1, in <module>
> 
> NameError: name 'odl' is not defined
> 
> /home/ehrhardt/repositories/git_ODL/odl/solvers/functional/default_functionals.py:905: UnexpectedException
>  [doctest] odl.solvers.functional.default_functionals.IndicatorNuclearNormUnitBall.__init__ 
> 2099             Exponent for the norm for the singular vectors.
> 2100 
> 2101         Examples
> 2102         --------
> 2103         Simple example, nuclear norm of matrix valued function with all ones
> 2104         in 3 points. The singular values are [2, 0], which has squared 2-norm
> 2105         2. Since there are 3 points, the expected total value is 6.
> 2106         Since the nuclear norm is larger than 1, the indicator is infinity.
> 2107 
> 2108         >>> r3 = odl.rn(3)
> UNEXPECTED EXCEPTION: NameError("name 'odl' is not defined",)
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.5/doctest.py", line 1321, in __run
>     compileflags, 1), test.globs)
> 
>   File "<doctest odl.solvers.functional.default_functionals.IndicatorNuclearNormUnitBall.__init__[0]>", line 1, in <module>
> 
> NameError: name 'odl' is not defined
> 
> /home/ehrhardt/repositories/git_ODL/odl/solvers/functional/default_functionals.py:2108: UnexpectedException
> _ [doctest] odl.solvers.functional.default_functionals.IndicatorZero.__init__ __
> 929         Parameters
> 930         ----------
> 931         space : `LinearSpace`
> 932             Domain of the functional.
> 933         constant : element in ``domain.field``, optional
> 934             The constant value of the functional
> 935 
> 936         Examples
> 937         --------
> 938         >>> space = odl.rn(3)
> UNEXPECTED EXCEPTION: NameError("name 'odl' is not defined",)
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.5/doctest.py", line 1321, in __run
>     compileflags, 1), test.globs)
> 
>   File "<doctest odl.solvers.functional.default_functionals.IndicatorZero.__init__[0]>", line 1, in <module>
> 
> NameError: name 'odl' is not defined
> 
> /home/ehrhardt/repositories/git_ODL/odl/solvers/functional/default_functionals.py:938: UnexpectedException
> _ [doctest] odl.solvers.functional.default_functionals.MoreauEnvelope.__init__ _
> 2208             is to be smoothed.
> 2209         sigma : positive float, optional
> 2210             The scalar ``sigma`` in the definition of the Moreau envelope.
> 2211             Larger values mean stronger smoothing.
> 2212 
> 2213         Examples
> 2214         --------
> 2215         Create smoothed l1 norm:
> 2216 
> 2217         >>> space = odl.rn(3)
> UNEXPECTED EXCEPTION: NameError("name 'odl' is not defined",)
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.5/doctest.py", line 1321, in __run
>     compileflags, 1), test.globs)
> 
>   File "<doctest odl.solvers.functional.default_functionals.MoreauEnvelope.__init__[0]>", line 1, in <module>
> 
> NameError: name 'odl' is not defined
> 
> /home/ehrhardt/repositories/git_ODL/odl/solvers/functional/default_functionals.py:2217: UnexpectedException
> __ [doctest] odl.solvers.functional.default_functionals.NuclearNorm.__init__ ___
> 1865         singular_vector_exp : {1, 2, inf}, optional
> 1866             Exponent for the norm for the singular vectors.
> 1867 
> 1868         Examples
> 1869         --------
> 1870         Simple example, nuclear norm of matrix valued function with all ones
> 1871         in 3 points. The singular values are [2, 0], which has squared 2-norm
> 1872         2. Since there are 3 points, the expected total value is 6.
> 1873 
> 1874         >>> r3 = odl.rn(3)
> UNEXPECTED EXCEPTION: NameError("name 'odl' is not defined",)
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.5/doctest.py", line 1321, in __run
>     compileflags, 1), test.globs)
> 
>   File "<doctest odl.solvers.functional.default_functionals.NuclearNorm.__init__[0]>", line 1, in <module>
> 
> NameError: name 'odl' is not defined
> 
> /home/ehrhardt/repositories/git_ODL/odl/solvers/functional/default_functionals.py:1874: UnexpectedException
>  [doctest] odl.solvers.functional.default_functionals.SeparableSum.__getitem__ _
> 1610             Object determining which parts of the sum to extract.
> 1611 
> 1612         Returns
> 1613         -------
> 1614         subfunctional : `Functional` or `SeparableSum`
> 1615             Functional corresponding to the given indices.
> 1616 
> 1617         Examples
> 1618         --------
> 1619         >>> space = odl.rn(3)
> UNEXPECTED EXCEPTION: NameError("name 'odl' is not defined",)
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.5/doctest.py", line 1321, in __run
>     compileflags, 1), test.globs)
> 
>   File "<doctest odl.solvers.functional.default_functionals.SeparableSum.__getitem__[0]>", line 1, in <module>
> 
> NameError: name 'odl' is not defined
> 
> /home/ehrhardt/repositories/git_ODL/odl/solvers/functional/default_functionals.py:1619: UnexpectedException
> __ [doctest] odl.solvers.functional.default_functionals.SeparableSum.__init__ __
> 1564         functional1, ..., functionalN : `Functional`
> 1565             The functionals in the sum.
> 1566             Can also be given as ``space, n`` with ``n`` integer,
> 1567             in which case the functional is repeated ``n`` times.
> 1568 
> 1569         Examples
> 1570         --------
> 1571         Create functional ``f([x1, x2]) = ||x1||_1 + ||x2||_2``:
> 1572 
> 1573         >>> space = odl.rn(3)
> UNEXPECTED EXCEPTION: NameError("name 'odl' is not defined",)
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.5/doctest.py", line 1321, in __run
>     compileflags, 1), test.globs)
> 
>   File "<doctest odl.solvers.functional.default_functionals.SeparableSum.__init__[0]>", line 1, in <module>
> 
> NameError: name 'odl' is not defined
> 
> /home/ehrhardt/repositories/git_ODL/odl/solvers/functional/default_functionals.py:1573: UnexpectedException
> ===================== 10 failed, 1 passed in 0.48 seconds ======================

**Comment by adler-j** [comment] 2017-06-23 09:32
This may be because you are not running the test from the odl ROOT folder, but from the odl subfolder (frustrating, i know). I.e. you are running from `~/repositories/git_ODL/odl` whereas the root would be `~/repositories/git_ODL`

Since you are not in the root folder, the tests do not get the proper test presets that are needed to run everything properly. Can you try running from the "true" root folder?

**Comment by adler-j** [comment] 2017-06-23 09:40
Hmm, I tested the above and that is not it, but I'm sure the bug is that you somehow do not have the odl plugin installed in pytest. Holger was the guy who touched this last, so perhaps you know why this is not the case?

**Comment by MatthiasJE** [comment] 2017-06-23 09:59
Yes, I am fairly sure. Here is the output if I do it again:
> ehrhardt@TPX1:~/repositories/git_ODL$ sudo -H pip install -e .
> Obtaining file:///home/ehrhardt/repositories/git_ODL
> Requirement already satisfied: future>=0.14 in /usr/lib/python2.7/dist-packages (from odl==0.6.1.dev0)
> Requirement already satisfied: numpy<1.13,>=1.9 in /usr/local/lib/python2.7/dist-packages (from odl==0.6.1.dev0)
> Requirement already satisfied: scipy>=0.14 in /usr/lib/python2.7/dist-packages (from odl==0.6.1.dev0)
> Installing collected packages: odl
>   Found existing installation: odl 0.6.1.dev0
>     Can't uninstall 'odl'. No files were found to uninstall.
>   Running setup.py develop for odl
> Successfully installed odl

**Comment by adler-j** [comment] 2017-06-23 13:28
Can you try a user level install instead? Also interesting that it says it cannot uninstall ODL, do you know why it says that?

Also, the pip message you printed here is for python 2, while your messages above are for python 3, so do you have multiple installations?

**Comment by MatthiasJE** [comment] 2017-06-23 13:32
> Also, the pip message you printed here is for python 2, while your messages above are for python 3, so do you have multiple installations?

Well spotted, that solved it. Thanks!

However, there is something strange again ... While Travis complains about my code, pytest does not:

> ehrhardt@TPX1:~/repositories/git_ODL$ pytest odl/solvers/functional/default_functionals.py 
> ============================= test session starts ==============================
> platform linux -- Python 3.5.2, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
> rootdir: /home/ehrhardt/repositories/git_ODL/odl, inifile: pytest.ini
> plugins: pep8-1.0.6, odl-0.6.1.dev0
> collected 11 items 
> 
> odl/solvers/functional/default_functionals.py ...........
> 
> ========================== 11 passed in 0.06 seconds ===========================

**Comment by MatthiasJE** [comment] 2017-06-23 13:33
Regarding the uninstall, no idea ... I suppose you guys are the experts :) @kohr-h  might know more?

**Comment by adler-j** [comment] 2017-06-23 21:59
It could be two reasons: First we run the pep8 tests, e.g. `pytest --pep8` which checks formatting, second we run both python 2 and python 3 tests. You can check the Travis output to see which it is.

**Comment by aringh** [comment] 2017-06-26 08:10
Regarding naming: I do not have a strong opinion, but to me `prior` is not confusing (although that might also just be that I am use to it). However, I have more often used KL, and in partucular then what we in `odl` call KL Cross Entropy, as regularizing functional and not for data matching. In that setting `prior` feels like a natural name. In any case, I think that the name should be the same in all 4 "KL-like" functionals.

On the same track, I think that a default prior of 1 is ok. In spectral estimation problem, the KL Cross Entropy becomes the (normalized) maximum [entropy solution by Burg](http://people.ece.umn.edu/~georgiou/files/HRTSA/me.html). However, again, if the KL functionals are used for data matching I completely understand if having a default value for the `prior` feels unnatural.

In concnlusion: I do not oppose chaining the naming, nor removing the default value. From the perspective above they make sense, but from a perspective when the functional is used for data matching they do not.

Also: the issue of `0 * log(0) = 0` seems to be partially handled already in the KL-Cross Entropy functional [by using](https://github.com/odlgroup/odl/blob/master/odl/solvers/functional/default_functionals.py#L1331-L1335) `scipy`'s `xlogy` functionality. In this case one for instance get
```python
>>> import numpy as np
>>> import scipy.special
>>> scipy.special.xlogy(0,0)
0.0
>>> scipy.special.xlogy(0,np.inf)
0.0
```
Would this work also for the KL-functional?

**Comment by kohr-h** [comment] 2017-06-26 11:04
Hi guys,

- @MatthiasJE you don't work with virtual environments, do you? Because the interaction of system-wide installed packages and user packages of the same name is... interesting. If somehow possible for you, I would advise to use either [`virtualenv`](https://virtualenv.pypa.io/) or [`conda`](https://conda.io/docs/). They will help you keep Python versions and packages sorted.
  Regarding the place from where test are run: Since ODL uses the pytest entry point mechanism and a custom plugin file, ODL needs to be installed for pytest to find these plugins. Apart from that, it should be relatively robust as to where the tests are run from. If ODL is installed with `pip install -e` it will test the local repo anyway, so running from outside the repo or from the repo root should be equivalent. The only hiccup is, as @adler-j points out, running just `pytest` from `/path/to/odl_repo/odl`, in which case no tests are found if I run it. But running specific files works in any case.
- Regarding naming, I'm not an expert in this and don't have a strong opinion. Probably a bit more explanation in [the docs](https://github.com/odlgroup/odl/blob/master/odl/solvers/functional/default_functionals.py#L1048-L1050) would already resolve the confusion.
  I'm thinking about including
    - that `prior` is a distribution (or stochastic process) that should be matched,
    - that in inverse problems this is usually given as data,
    - that `prior` corresponds to the `g` in the mathematical explanation,
    - why `space.one()` is chosen as default.
- I also noted that `KullbackLeibler.gradient` does not have a math formula, I post it here for reference:
  ```
  The gradient of `KullbackLeibler` with ``prior`` :math:`g` is given as

  .. math::

      \\nabla F(x) = 1 - \frac{g}{x}.
  ```
- Regarding `xlogy`: Well done @aringh. In fact SciPy's function is implemented as `ufunc` and will be a lot faster than the hand-written version with conditional arrays (I get roughly x2 speedup on my machine). So yes, definitely use it. The most efficient implementation would (probably) be
  ```python
  np.divide(y, x, out=out)
  scipy.special.xlogy(x, out, out=out)
  out += x
  out -= y
  ```
  The cases that produces `NaN` (`x` contains 0 or `y / x` has non-positive entries) should correctly produce `NaN` output while the "0 log 0" case is fixed.

**Comment by adler-j** [comment] 2017-06-27 14:39
Closing this since the issue is done. It seems we have more related issues, so anyone who wants that done, please open a new issue.

**Closed by adler-j** 2017-06-27 14:39 UTC
