### ISSUE TITLE
RectPartition has no length

### ISSUE THREAD

**Issue by ozanoktem** [odlgroup/odl#423] opened 2016-06-01 09:35 UTC
Sometimes we need to know the number of partitions. Trying to execute the `len` command on a partition gives an error message;
```
TypeError: object of type 'RectPartition' has no len()
```

**Comment by kohr-h** [comment] 2016-06-02 07:50
Why was this auto-closed? The PR was not merged. Bug in GitHub?

**Comment by adler-j** [comment] 2016-06-02 09:09
The issue is open, what is the bug?

**Comment by kohr-h** [comment] 2016-06-02 09:48
Hm, I must have looked in the wrong line in notifications. Was sure the issue appeared as closed. Never mind.

**Closed** 2016-06-03 20:48 UTC
Labels: needs improvement, odl core
