### ISSUE TITLE
algorithm is slowing down over the iterations

### ISSUE THREAD

**Issue by mehrhardt** [odlgroup/odl#1291] opened 2018-02-12 19:08 UTC
again (possibly) not an issue with ODL. I am implementing examples for SPDHG and for one example I noticed that ODL's PDHG became slower over the course of the iterations. This perhaps has to do with my implementation of some functionals. The example I am talking about is the deblurring example in #1194.

For example timings (per iteration) are as below where the final iterations are up to 5 times slower than the initial ones. Any ideas what may cause this?

> iter:   0, time:  0.03 s
> iter:   1, time:  0.03 s
> iter:   2, time:  0.03 s
> iter:   3, time:  0.03 s
> iter:   4, time:  0.03 s
> iter:   5, time:  0.04 s
> iter:   6, time:  0.04 s
> iter:   7, time:  0.04 s
> iter:   8, time:  0.04 s
> iter:   9, time:  0.04 s
> iter:  10, time:  0.04 s
> iter:  11, time:  0.04 s
> iter:  12, time:  0.05 s
> iter:  13, time:  0.05 s
> iter:  14, time:  0.05 s
> iter:  15, time:  0.05 s
> iter:  16, time:  0.05 s
> iter:  17, time:  0.06 s
> iter:  18, time:  0.05 s
> iter:  19, time:  0.06 s
> iter:  20, time:  0.05 s
> iter:  21, time:  0.06 s
> iter:  22, time:  0.06 s
> iter:  23, time:  0.06 s
> iter:  24, time:  0.06 s
> iter:  25, time:  0.06 s
> iter:  26, time:  0.06 s
> iter:  27, time:  0.06 s
> iter:  28, time:  0.06 s
> iter:  29, time:  0.07 s
> iter:  30, time:  0.07 s
> iter:  31, time:  0.07 s
> iter:  32, time:  0.07 s
> iter:  33, time:  0.07 s
> iter:  34, time:  0.10 s
> iter:  35, time:  0.07 s
> iter:  36, time:  0.07 s
> iter:  37, time:  0.07 s
> iter:  38, time:  0.08 s
> iter:  39, time:  0.08 s
> iter:  40, time:  0.08 s
> iter:  41, time:  0.08 s
> iter:  42, time:  0.08 s
> iter:  43, time:  0.08 s
> iter:  44, time:  0.08 s
> iter:  45, time:  0.08 s
> iter:  46, time:  0.09 s
> iter:  47, time:  0.09 s
> iter:  48, time:  0.09 s
> iter:  49, time:  0.09 s
> iter:  50, time:  0.09 s
> iter:  51, time:  0.09 s
> iter:  52, time:  0.10 s
> iter:  53, time:  0.10 s
> iter:  54, time:  0.10 s
> iter:  55, time:  0.09 s
> iter:  56, time:  0.10 s
> iter:  57, time:  0.10 s
> iter:  58, time:  0.10 s
> iter:  59, time:  0.10 s
> iter:  60, time:  0.10 s
> iter:  61, time:  0.10 s
> iter:  62, time:  0.11 s
> iter:  63, time:  0.11 s
> iter:  64, time:  0.11 s
> iter:  65, time:  0.11 s
> iter:  66, time:  0.11 s
> iter:  67, time:  0.12 s
> iter:  68, time:  0.11 s
> iter:  69, time:  0.11 s
> iter:  70, time:  0.12 s
> iter:  71, time:  0.12 s
> iter:  72, time:  0.12 s
> iter:  73, time:  0.12 s
> iter:  74, time:  0.12 s
> iter:  75, time:  0.12 s
> iter:  76, time:  0.12 s
> iter:  77, time:  0.12 s
> iter:  78, time:  0.13 s
> iter:  79, time:  0.13 s
> iter:  80, time:  0.13 s
> iter:  81, time:  0.13 s
> iter:  82, time:  0.13 s
> iter:  83, time:  0.13 s
> iter:  84, time:  0.13 s
> iter:  85, time:  0.14 s
> iter:  86, time:  0.13 s
> iter:  87, time:  0.14 s
> iter:  88, time:  0.14 s
> iter:  89, time:  0.14 s
> iter:  90, time:  0.15 s
> iter:  91, time:  0.16 s
> iter:  92, time:  0.14 s
> iter:  93, time:  0.14 s
> iter:  94, time:  0.14 s
> iter:  95, time:  0.14 s
> iter:  96, time:  0.14 s
> iter:  97, time:  0.15 s
> iter:  98, time:  0.15 s
> iter:  99, time:  0.15 s

**Comment by adler-j** [comment] 2018-02-12 20:18
This is very likely a duplicate of #1270, are you using scalar multiplication?

**Comment by mehrhardt** [comment] 2018-02-13 10:14
Perhaps this is true. I could isolate the cause of the error to be very likely in this function call. 
```
            def __call__(self, x, out=None):

                s = self.sigma
                y = self.data
                r = self.background

                # TODO: Make memory and CPU/GPU efficient
                # TODO: Make sure it works for data = 0

                if out is None:
                    out = self.domain.element()

                sr = s * r
                sy = s * y

                # if x < 1 - y / r, then
                # TODO: formulas missing
                i = x.ufuncs.less(1 - y / r)
#                out.assign(i * ((y * x - s * r * y + s * r**2) /
#                                (y + s * r**2)))
                out[i] = ((y[i] * x[i] - sr[i] * y[i] + sr[i] * r[i]) /
                          (y[i] + sr[i] * r[i]))

                # else:
                # TODO: formulas missing
                i = i.ufuncs.logical_not()
#                out += i * (0.5 * (x + s * r + 1 - ((x + s * r - 1)**2 +
#                                                    4 * s * y).ufuncs.sqrt()))
                out[i] = 0.5 * (x[i] + sr[i] + 1 -
                                ((x[i] + sr[i] - 1)**2 +
                                 4 * sy[i]).ufuncs.sqrt())

                return out
```

**Comment by adler-j** [comment] 2018-02-13 10:23
Is there any chance you could provide a minimal working example of this?

Also, can you try rebasing on master, it seems #1270 is not an issue any more (for unknown reasons).

**Comment by mehrhardt** [comment] 2018-02-13 10:41
I did rebase, but this wouldn't change anything. Here is a "minimal" example:
```


import odl


class KullbackLeiblerSmoothConvexConj(odl.solvers.Functional):
    def __init__(self, space, data, background):
        super().__init__(space=space, linear=False)

        self.__data = data
        self.__background = background

    @property
    def data(self):
        """The data in the Kullback-Leibler functional."""
        return self.__data

    @property
    def background(self):
        """The background in the Kullback-Leibler functional."""
        return self.__background

    @property
    def proximal(self):

        space = self.domain
        y = self.data
        r = self.background

        class ProxKullbackLeiblerSmooth_convexconj(odl.Operator):

            """Proximal operator of the convex conjugate of the smooth
            Kullback-Leibler functional.
            """

            def __init__(self, sigma):
                """Initialize a new instance.

                Parameters
                ----------
                sigma : positive float
                    Step size parameter
                """
                self.sigma = float(sigma)
                self.background = r
                self.data = y
                super().__init__(domain=space, range=space, linear=False)

            def _call(self, x, out):

                s = self.sigma
                y = self.data
                r = self.background

                sr = s * r
                sy = s * y

                # if x < 1 - y / r, then
                # TODO: formulas missing
                i = x.ufuncs.less(1 - y / r)
#                out.assign(i * ((y * x - s * r * y + s * r**2) /
#                                (y + s * r**2)))
                out[i] = ((y[i] * x[i] - sr[i] * y[i] + sr[i] * r[i]) /
                          (y[i] + sr[i] * r[i]))

                # else:
                # TODO: formulas missing
                i = i.ufuncs.logical_not()
#                out += i * (0.5 * (x + s * r + 1 - ((x + s * r - 1)**2 +
#                                                    4 * s * y).ufuncs.sqrt()))
                out[i] = 0.5 * (x[i] + sr[i] + 1 -
                                ((x[i] + sr[i] - 1)**2 +
                                 4 * sy[i]).ufuncs.sqrt())

                return out

        return ProxKullbackLeiblerSmooth_convexconj


X = odl.uniform_discr([0, 0], [100, 100], [100, 100])

background = 300 * X.one()
data = 300 * X.one()

f = KullbackLeiblerSmoothConvexConj(X, data, background)
x = X.zero()

callback = (odl.solvers.CallbackPrintIteration(fmt='iter:{:4d}',
                                               step=1, end=', ') &
            odl.solvers.CallbackPrintTiming(fmt='time: {:5.2f} s',
                                            step=1, cumulative=False))

for i in range(100):
    f.proximal(1)(x)
    callback(x)
```

**Comment by adler-j** [comment] 2018-02-14 11:03
So this is a much smaller working example, I'm working on fixing this:

```python
import odl

X = odl.rn([100, 100])
x = X.zero()

callback = (odl.solvers.CallbackPrintIteration(fmt='iter:{:4d}',
                                               step=1, end=', ') &
            odl.solvers.CallbackPrintTiming(fmt='time: {:5.2f} s',
                                            step=1, cumulative=False))

for i in range(100):
    for j in range(100):
        x[::2, ::2]
    callback(x)
```

**Comment by mehrhardt** [comment] 2018-02-14 11:07
Oh, wow. I did not expect such an example to have the same behaviour. I tested some other algorithms with prox operators for the l2 norm squared, Huber etc and they were not slowing down. Thus, I though it would be something specific about the function that I coded.

**Comment by adler-j** [comment] 2018-02-14 11:10
It had to do with `available_dtypes` which is called inside `__init__`. Basically we had a minor error which caused us to increase it linearly in size for each `__init__` call, which just happens to happen every time we do indexing.

**Comment by adler-j** [comment] 2018-02-14 11:13
Overall this is obvious new problems due to the tensor branch comming in lately and we're still squashing minor bugs like these. Thank you so much for the report! This should also speed up the test suite a bit.

**Closed** 2018-02-14 12:02 UTC

**Comment by mehrhardt** [comment] 2018-02-14 12:06
Perfect, your solution works very well!

**Comment by aringh** [comment] 2018-02-14 21:43
For later reference: the PR was #1294. Also: I got a speed up factor of about 6 in the test suite on my local machine, so pretty nice! ^^ Good catch!

**Comment by adler-j** [comment] 2018-02-14 22:27
Great to hear! This is why we occasionally do some performance tests on the main test suite.
