### ISSUE TITLE
numpy on product space elements of product space elements

### ISSUE THREAD

**Issue by mehrhardt** [odlgroup/odl#1404] opened 2018-06-29 18:21 UTC
The title might sound confusing, so just consider the following example

```
import odl
import numpy as np

X = odl.rn(3)
Y = odl.ProductSpace(X, X**2)

y = 2 * Y.one()

y_sqrt = np.sqrt(y)
y_sqrt2 = Y.element([np.sqrt(yy) for yy in y])
```

I would like `y_sqrt = np.sqrt(y)` to work in ODL and to be equal to `y_sqrt2`. This, however, is not the case. Why would (or should) ODL not like?

**Comment by adler-j** [comment] 2018-06-29 18:30
This doesn't work since we havn't properly implemented the interface for this (which btw, is rather new). The issue number tracking this is #1301, once that's in you should be fine.

**Comment by adler-j** [comment] 2018-06-29 19:12
I'll actually close this as a duplicate of that, stay tuned :)

**Closed by adler-j** 2018-06-29 19:12 UTC
