### ISSUE TITLE
Error with Test Script

### ISSUE THREAD

**Issue by Sebi9496** [odlgroup/odl#937] opened 2017-02-22 20:59 UTC
Hi all,

I installed ODL according to the description in a conda environment. Running the odl.test() file gave me the following error message:

```
part.cell_boundary_vecs[1]
Expected:
    array([-0.25,  0.25,  0.75,  3.  ])
Got:
    array([-0.25,  0.25,  0.75,  1.25])
```

C:\Users\Sebastian\Miniconda3\envs\odl-py36\lib\site-packages\odl\discr\partition.py:845: DocTestFailure
!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!

Can you help me with this issue? (The first 70 tests seemed to be fine.) Do you need any additional information?

Best,
Sebastian

**Comment by kohr-h** [comment] 2017-02-22 22:02
Hi @Sebi9496. Thanks for the report. This is a known issue, see #874. It's not entirely clear yet why it fails, but it only occurs under Python 3.6 (which you are using). Probably the implementation of that feature will change from using dictionaries to using tuples.

**Comment by Sebi9496** [comment] 2017-02-22 23:05
Can I still use Python 3.6 then, or will this affect a whole range of things then? If this is causing no major problems, I would prefer not to set up a new environment...

**Comment by kohr-h** [comment] 2017-02-22 23:09
> Can I still use Python 3.6 then, or will this affect a whole range of things then? If this is causing no major problems, I would prefer not to set up a new environment...

It should be fine to use. The failing test is a corner case, it's a seldom used option to a certain class. I'm using myself Python 3.6 since it's out and I haven't had any problems in practice.

That said, it should be fixed anyway asap. Just for myself, the "p" is "not this week" :-)

**Comment by adler-j** [comment] 2017-02-23 13:09
Closing this as duplicate of #874, please continue the discussion there!

**Closed by adler-j** 2017-02-23 13:09 UTC
Labels: bug
