### ISSUE TITLE
string representation of ODL objects

### ISSUE THREAD

**Issue by mehrhardt** [odlgroup/odl#1196] opened 2017-10-16 16:03 UTC
The string representation of ODL objects needs to be improved. My code did result in an error, but the error message was not shown anymore with 500 lines buffering in the ipython console because the string of the ODL object involved was too long. Here is a **snippet** of the output.

```
... **a lot** more lines ...
    DiscreteLp(
        FunctionSpace(IntervalProd([3.0473448739820994, -28.284271247461902], [3.1415926535897931, 28.284271247461902]), out_dtype='float32'),
        uniform_partition([3.0473448739820994, -28.284271247461902], [3.1415926535897931, 28.284271247461902], (1, 200)),
        rn(200, 'float32', weighting=0.02666),
        axis_labels=('$\\varphi$', '$s$')
    ),
    DiscreteLp(
        FunctionSpace(IntervalProd([3.0630528372500487, -28.284271247461902], [3.1415926535897931, 28.284271247461902]), out_dtype='float32'),
        uniform_partition([3.0630528372500487, -28.284271247461902], [3.1415926535897931, 28.284271247461902], (1, 200)),
        rn(200, 'float32', weighting=0.02221),
        axis_labels=('$\\varphi$', '$s$')
    ),
    DiscreteLp(
        FunctionSpace(IntervalProd([3.0787608005179976, -28.284271247461902], [3.1415926535897931, 28.284271247461902]), out_dtype='float32'),
        uniform_partition([3.0787608005179976, -28.284271247461902], [3.1415926535897931, 28.284271247461902], (1, 200)),
        rn(200, 'float32', weighting=0.01777),
        axis_labels=('$\\varphi$', '$s$')
    ),
    DiscreteLp(
        FunctionSpace(IntervalProd([3.0944687637859465, -28.284271247461902], [3.1415926535897931, 28.284271247461902]), out_dtype='float32'),
        uniform_partition([3.0944687637859465, -28.284271247461902], [3.1415926535897931, 28.284271247461902], (1, 200)),
        rn(200, 'float32', weighting=0.01333),
        axis_labels=('$\\varphi$', '$s$')
    ),
    DiscreteLp(
        FunctionSpace(IntervalProd([3.1101767270538954, -28.284271247461902], [3.1415926535897931, 28.284271247461902]), out_dtype='float32'),
        uniform_partition([3.1101767270538954, -28.284271247461902], [3.1415926535897931, 28.284271247461902], (1, 200)),
        rn(200, 'float32', weighting=0.008886),
        axis_labels=('$\\varphi$', '$s$')
    ),
    uniform_discr([3.1258846903218442, -28.284271247461902], [3.1415926535897931, 28.284271247461902], (1, 200), dtype='float32', axis_labels=('$\\varphi$', '$s$'))
)
``` 
A few things that one can easily notice is that the precision of the numbers can be shortened and newlines be removed. In addition, does one really need things like axis_labels?

**Comment by kohr-h** [comment] 2017-10-16 21:10
I generally agree. A major part of this is fixed on the tensor branch, but maybe it would make sense to backport the changes. And yes, `axis_labels` shouldn't be printed since it's not an essential property of the space.

But such a long output is a bit unusual in any case. Did you make a huge product space? If yes, the only thing that can be done is to simplify the individual strings, but if they're all different you get all of them printed separately.
That said, we could think about cropping the output for more than, say, 6 spaces.

**Comment by mehrhardt** [comment] 2017-10-17 11:02
Yes, this is a large product space but when slicing geometries in tomography you will always end up with these things. Limiting it to a fixed number of spaces sounds good to me. If one wants to look at individual spaces, one can still do this manually.

In addition I strongly discourage to print numbers in too high precision. This does not add any meaningful information but just overfloats the output. I came across this problem several times in a variety of situations, not only for product spaces.

**Comment by adler-j** [comment] 2017-10-17 11:17
I agree with @mehrhardt on all points here, and limiting the number is something we already do for e.g. arrays.

W.r.t `axis_labels`, I'm not so sure since they are actually part of the space and needed to reproduce it properly.

Another and highly related issue is stuff like this:

```python
>>> spc = odl.uniform_discr([0, 0, 0], [1, 1, 1], [128, 128, 128])
>>> op = odl.IdentityOperator(spc)
>>> op * spc.one()
OperatorRightVectorMult(IdentityOperator(uniform_discr([0.0, 0.0, 0.0], [1.0, 1.0, 1.0], (128, 128, 128))), uniform_discr([0.0, 0.0, 0.0], [1.0, 1.0, 1.0], (128, 128, 128)).element([[[1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0],
 ...,
 [1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0]],
 ...,
 [[1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0],
 ...,
 [1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, ..., 1.0, 1.0, 1.0]]]))
```

I would suggest we severely reduce this to something like this, if possible

```python
>>> spc = odl.uniform_discr([0, 0, 0], [1, 1, 1], [128, 128, 128])
>>> op = odl.IdentityOperator(spc)
>>> op * spc.one()
OperatorRightVectorMult(IdentityOperator(uniform_discr([0.0, 0.0], [1.0, 1.0], (128, 128))), uniform_discr([0.0, 0.0], [1.0, 1.0], (128, 128)).element(...))
```

alternatively we can include some summary statistics

```python
>>> spc = odl.uniform_discr([0, 0, 0], [1, 1, 1], [128, 128, 128])
>>> op = odl.IdentityOperator(spc)
>>> op * spc.one()
OperatorRightVectorMult(IdentityOperator(uniform_discr([0.0, 0.0], [1.0, 1.0], (128, 128))), uniform_discr([0.0, 0.0], [1.0, 1.0], (128, 128)).element([array with mean 1.0 and std 0.0]))
```

**Comment by mehrhardt** [comment] 2017-10-17 11:29
These are good points. I generally prefer the latter option. We probably want to limit statistics to "small" objects like less than 1M(?) components. For large scale objects I think your former suggestion is better.

**Comment by kohr-h** [comment] 2017-10-17 13:19
> In addition I strongly discourage to print numbers in too high precision. This does not add any meaningful information but just overfloats the output. I came across this problem several times in a variety of situations, not only for product spaces.

That comes from conversion to list (`array.tolist()`) in `repr`. I replaced that by a nicer array printing function on the mentioned branch, will try to backport that stuff.

I'm not so sure about the array statistics, though. Does it really help? Computing average and standard deviation is just one Numpy call each. I find it better to have one way of printing arrays, with truncation when things become too large. The only thing I find bad in the original output is that it starts on the first line.

Regarding axis labels and similar, I think we should only print in `repr` what is relevant to `__eq__`. `axis_labels` isn't, and for tomography it's just visual noise.

**Closed** 2017-10-22 15:14 UTC
