### ISSUE TITLE
Insecure connection warning on documentation website

### ISSUE THREAD

**Issue by dmpelt** [odlgroup/odl#644] opened 2016-10-11 18:15 UTC
From my workstation at Berkeley Lab, I get the following warning when trying to access the ODL documentation website (https://odlgroup.github.io/odl/):

```
The owner of odlgroup.github.io has configured their website improperly. 
To protect your information from being stolen, Firefox has not connected to this website.

odlgroup.github.io uses an invalid security certificate. 
Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

Firefox only lets me access the website using an exception. I don't know whether this is a GitHub problem or something in the ODL website configuration, but other `github.io` websites seem to be working without problem.

**Comment by adler-j** [comment] 2016-10-11 21:54
Not able to reproduce this locally at any of my machines using IE or chrome. Some googling indicates that it may be temporary. Does the problem persist?

**Comment by adler-j** [comment] 2016-10-13 07:25
bump

**Comment by aringh** [comment] 2016-10-13 08:08
I have tried it on my local machine too, and unfortunately I'm not able to reproduce the error (I'm running Firefox).

**Comment by dmpelt** [comment] 2016-10-13 21:05
Might be something on my end then... Could be that the website is blocked here for some reason. I will try to figure out here what is going on.

**Comment by adler-j** [comment] 2016-10-14 06:18
If you find anything we'd love to hear how you reproduced this, but currently I suspect that your certificate authority may simply be lacking this authority.

**Comment by adler-j** [comment] 2016-11-02 12:25
Any update on this? Else I say we close this since it doesn't seem like we can do anything locally.

**Comment by kohr-h** [comment] 2016-11-02 14:42
I think this came from a major fuckup of some certificate authorities which invalidated major websites' certificates for a lot of users. I guess it has rippled out by now.

**Closed** 2016-11-02 16:07 UTC
Labels: close?, distribution, documentation
