### ISSUE TITLE
Merge LDDMM solver

### ISSUE THREAD

**Issue by chongchenmath** [odlgroup/odl#1011] opened 2017-05-29 09:02 UTC
The odl_lddmm in my account needs to be merged. How to do it? @adler-j @kohr-h

**Comment by adler-j** [comment] 2017-05-29 09:36
Can you link exactly what you want merged? Also you should be able to make a pull request.

**Comment by chongchenmath** [comment] 2017-05-29 09:46
Thank you. https://github.com/chongchenmath/odl_lddmm

**Comment by adler-j** [comment] 2017-05-29 12:51
It was my understanding that that package should stay external for now? E.g. like my external packages 

https://github.com/adler-j/odl-stem-examples

https://github.com/adler-j/spectral_projector

https://github.com/adler-j/spectral_ct_examples

https://github.com/adler-j/lie_grp_diffeo

https://github.com/adler-j/learned_gradient_tomography

To the best of my understanding LDDMM is not a general purpose algorithm that others would want to use "in general", just like my above examples.

With that said, the package you have linked does not seem to run with the current version of ODL, i.e. there are some changes that you need pushed to ODL for it to work. I suggest you make a pull request for those things.

**Comment by chongchenmath** [comment] 2017-05-29 13:29
Here the LDDMM solver is independent. It seems to work well on the current version of ODL. The used head is:

``````
from __future__ import print_function, division, absolute_import
from future import standard_library
import numpy as np
from odl.discr import (Gradient, ResizingOperator)
from odl.trafos import FourierTransform
from odl.space import ProductSpace
from odl.operator import DiagonalOperator
from odl.deform.linearized import _linear_deform
standard_library.install_aliases() 
``````

Is it that possible to make a pull request directly?

**Comment by adler-j** [comment] 2017-05-29 13:57
Well "it seems to work" does not imply that it does actually do so, among other things it has [this line](https://github.com/chongchenmath/odl_lddmm/blob/4e5d7f3fa1f1e156c3e4392ef31ca65f08f29e94/Recon_LDDMM.py#L140-L142), which is not in ODL since ODL has no function named "LDDMM_gradient_descent_solver".

Except for that, is there any specific reason we want this solver to be part of ODL? Why this but not (for example) any of the packages I listed above?

**Comment by ozanoktem** [comment] 2017-05-29 18:49
I don't agree with the comparison that you make @adler-j regarding LDDMM and the packages you list. Most of them are in one way or the other tied to a modality. LDDMM on the other hand is a fairly generic manner for generating diffeomorphisms that can act on various image features by means of different group actions. There may be reasons for having the LDDMM package stay external for now, but I see it as an integral part of a deformations functionality in ODL. The computation of various group actions and their derivatives when combined wth functionals along with the machinery for generating velocity fields from a RKHS kernel are indeed generic enough to merit a place in ODL.

**Comment by adler-j** [comment] 2017-05-30 00:24
Well, wouldn't you argue that https://github.com/adler-j/lie_grp_diffeo is far more general than LDDMM? Not to mention the machine learning examples? Or what about [https://github.com/adler-j/mfcm_article](https://github.com/adler-j/mfcm_article), where I have basically implemented a segmentation method?

Anyway my main point here is that ODL should NOT (and I am very certain about this) be our personal playground where we put our latest code from our latest article. ODL should (imo) contain two primary things:

* The tools needed to implement the latest fancy stuff
* Default implementations of well known algorithms

In this case, neither applies.

The main reason for this is simple: maintainance creep. The more stuff we add to ODL, the more time we have to spend maintaining it, updating to new versions, etc. That takes time, and especially given that noone of the core maintainers (me/holger) are working particularily much in deformations it will take even more time in this case. In addition, removing stuff from a library is very hard, so by adding more stuff (which we currently do not know if they will be widely used in the future or not) we just keep increasing the maintainance load for marginal gain.

One option that we could do is to put LDDMM under `odl.contrib.deform` until it is more mature. But then chong would be in charge of maintaining it.

Still, I think it is needed for your LDDMM article to keep an external repository where you have all the examples you present in the article available so that people can reproduce them. So you would still need to keep that library. This is especially true if you want to add images.

**Comment by kohr-h** [comment] 2017-05-31 18:25
I have to assist @adler-j here. Of course, LDDMM is quite general-purpose, but it still falls into the category "advanced stuff that one wouldn't necessarily expect in a general-purpose library". And the maintenance issue is real, already with our own code. I don't really want to think about having to debug code that I didn't write myself or don't understand conceptually after a reasonable time.

For instance, I'm currently adding all the multigrid code to a separate repository. Whenever I feel that some functionality would actually make sense in core ODL, it's way easier to go this way and add it, than to remove code after realizing that nobody really understands what's happening or nobody can really verify the correctness.

So please don't feel degraded in any way by having to make an external repo instead of being part of the core. It's not about quality, it's more about purpose, scope and maintainability in this case.

See also #1016

**Comment by adler-j** [comment] 2017-06-29 08:40
This is settled for now with the LDDMM having its own repository. If we find that some other users start depending on it, we should make an effort to move it into `odl.contrib.deform`.

**Closed by adler-j** 2017-06-29 08:40 UTC
Labels: help wanted, odl deform
