### ISSUE TITLE
multi indexing of functions

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#943] opened 2017-02-28 09:34 UTC
I guess this issue was raised somewhere already but I could not find it. So please apologies my duplicate. 

In all my applications, the images are 2 or 3 dimensional so it would be good if ODL was supporting multi indexing. Here an example that does **not** work:

```python
>>> X = odl.uniform_discr(min_pt=[-1, -1], max_pt=[1, 1], shape=[128, 128])
>>> x = X.one()
>>> x[1,1]
```

```
Traceback (most recent call last):

  File "<ipython-input-13-3e593ebbc211>", line 1, in <module>
    x[1,1]

  File "odl/discr/discretization.py", line 326, in __getitem__
    return self.ntuple.__getitem__(indices)

  File "odl/space/npy_ntuples.py", line 367, in __getitem__
    arr = self.data[indices]

IndexError: too many indices for array
```

Of course by now I know a way around it: `x.asarray()[1,1]` However, this does not satisfy my needs as I want to write code that I can _interchangeably_ with ODL or numpy. Is it so difficult to implement this directly, e.g. `x[1,1] := x.asarray()[1,1]`?

**Comment by adler-j** [comment] 2017-02-28 10:36
> I guess this issue was raised somewhere already but I could not find it. So please apologies my duplicate.

There is a huge effort in this direction, started with issue #342, then continued in #731, #857, #907, #908. The pull requests #739 and #861 are our WIP implementations of this.

> Of course by now I know a way around it: `x.asarray()[1,1]` However, this does not satisfy my needs as I want to write code that I can _interchangeably_ with ODL or numpy. Is it so difficult to implement this directly, e.g. `x[1,1] := x.asarray()[1,1]`?

We agree and we're working on it. However, on a deeper level this is non-trivial since we want to be able to support several backends, and up until lately there were no good GPU backends that allowed that syntax (there now is in [libgpuarray](https://github.com/Theano/libgpuarray)).

You can anyway expect this feature to come to ODL Soon®.

**Comment by kohr-h** [comment] 2017-02-28 11:29
Just for the record, I'm pushing this stuff for finalization currently, including GPU support. So hang tight :-)

**Comment by kohr-h** [comment] 2017-03-17 22:46
Closing as duplicate of ~10 issues taken together.

**Closed by kohr-h** 2017-03-17 22:46 UTC
