### ISSUE TITLE
Problem with numpy arrays as step lengths to proximal operators?

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#1268] opened 2018-01-14 18:35 UTC
While working on the Bregman distance functional in #1267 I encountered the following bug:

```python
import odl
import numpy as np

space = odl.uniform_discr(0, 1, 10)
point = space.one()

l2_sq = odl.solvers.L2NormSquared(space)
breg = odl.solvers.BregmanDistance(l2_sq, point)

sigma_array = np.array(0.4)
sigma = float(sigma_array)

tmp = breg.proximal
tmp(sigma)
tmp(sigma_array)
```
which gives a very short call stack and a cryptical error message.
```
Traceback (most recent call last):

  File "<ipython-input-4-2907eb4487d1>", line 1, in <module>
    runfile('[...]/tmp.py', wdir='[...]')

  File "[...]/miniconda3/envs/odl-py36/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "[...]/miniconda3/envs/odl-py36/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "[...]/tmp.py", line 15, in <module>
    tmp(sigma_array)

TypeError: unhashable type: 'numpy.ndarray'
```
Does anyone know what the problem is?

**Comment by sbanert** [comment] 2018-01-14 19:08
The problem is that the argument of the proximal factory is cached in order to increase the performance by not creating copies of the same operator. This does not work, since numpy.ndarray and hence cannot be hashed. This behaviour is switched off once #1166 is merged. You could try replacing the following line by sig = float(self.sigma).

https://github.com/odlgroup/odl/blob/3b75c07a4bc21dd76346d2db29651256285c253a/odl/solvers/nonsmooth/proximal_operators.py#L926.

**Comment by kohr-h** [comment] 2018-01-14 20:02
Well explained, @sbanert. 

A general remark: This is one of the rare cases where we store user input as-is. It's easier for sure, since sanitizing code needs to be written and maintained. But the downside is that you never know for sure what you have stored. Still, you have a type in mind (here `float`) that you implicitly assume when writing depending code, and when that assumption is violated, bad things can happen.
So in general, whenever we store something as a class attribute, we try to *always* store a well-defined type or, limit the possible types to 2 or 3 (when sanitizing code would be expensive), or in the worst case at least write a comment that we need to treat the attribute as user-defined and cannot know for sure what it is (at least that's what we should do in that case 😄).

So the short version of this is: when storing user input, always sanitize.

**Comment by aringh** [comment] 2018-01-15 14:16
Ok, thank you both @sbanert and @kohr-h for the explanation.

Regarding the suggested change: that is already happening in the init method, 5 lines above. That is why I did not understand what was happening. Exactly when is exactly what cashed and hashed?

**Comment by adler-j** [comment] 2018-01-21 01:10
Should this be fixed now on master @sbanert?

**Comment by sbanert** [comment] 2018-01-25 14:54
Seems to be fixed now. @aringh’s code does no longer trigger an error when I rebase his branch on the current master.

**Closed** 2018-01-25 15:00 UTC
