### ISSUE TITLE
Bug: no update with conjugate gradient, os-dependency? 

### ISSUE THREAD

**Issue by davlars** [odlgroup/odl#732] opened 2016-11-24 11:47 UTC
I'm running odl on the following system: 

Ubuntu 16.04.1 LTS
`odl.__version__ : 0.5.2`
`numpy.__version__: 1.11.2`
`python.__version__: 2.7.12`

With the following example, trying to reconstruct with conjugate gradient on normal equations (`odl.solvers.conjugate_gradient_normal`) gives no visual update. Instead the reconstruction is stuck on what seems to be the first iterate. This is however not the case when trying with e.g. landweber (wihch seems to work fine).

To make it even more interesting, this is not reproducible on a windows-system. 

Could someone try to re-run it on a linux-os to see if the error is local? 

```python
# Test run
import odl
import numpy as np

# Set geometry parameters
volumeSize = np.array([10, 10, 10]) #mm?
volumeOrigin = np.array([-5, -5, -5.0]) #mm?
nVoxels = np.array([100,100,100])
detectorSize = np.array([30.0, 3.0])
nPixels = [300, 30]
detectorOrigin = -detectorSize/2

# Discrete reconstruction space
discr_reco_space = odl.uniform_discr(volumeOrigin,volumeOrigin + volumeSize,
                                     nVoxels, dtype='float32')

#Define projection geometry
angle_partition = odl.uniform_partition(0, 2 * np.pi, 360)

# Detector: uniformly sampled, n = nPixels, min = detectorOrigin, max = detectorOrigin+detectorSize
detector_partition = odl.uniform_partition(detectorOrigin, detectorOrigin+detectorSize, nPixels)

# Spiral has a pitch of pitch_mm, we run n_turns rounds (due to max angle = 8 * 2 * pi)
geom = odl.tomo.HelicalConeFlatGeometry(angle_partition, 
                                        detector_partition, 
                                        src_radius=250, 
                                        det_radius=250,
                                        pitch=0,
                                        pitch_offset=0)

A = odl.tomo.RayTransform(discr_reco_space, geom, impl='astra_cuda')
# A = odl.trafos.FourierTransform(discr_reco_space) also fails
phantom = odl.phantom.cuboid(A.domain)
rhs = A(phantom)

# Reconstruct
partialPrintIter = odl.solvers.CallbackPrintIteration() #Print iterations
partialShowIter = odl.solvers.CallbackShow(coords=[None, 2, None]) #Show parital reconstructions

# THIS FAILS

#partialIter = odl.solvers.util.PrintIterationPartial()
x = discr_reco_space.zero()
odl.solvers.conjugate_gradient_normal(A, x, rhs, niter=1000, callback = partialPrintIter & partialShowIter)

# THESE WORK JUST FINE
#odl.solvers.conjugate_gradient(A.adjoint * A, x, A.adjoint(rhs), niter=1000, callback = partialPrintIter & partialShowIter)
#odl.solvers.landweber(A, x, rhs, niter=1000, omega=0.1, callback = partialPrintIter & partialShowIter)
```

Edit: @adler-j fixed formatting.

**Comment by adler-j** [comment] 2016-11-24 13:58
The windows system in question is mine, where this code performs as expected. I do however use the latest odl from master, so that may be the issue.

**Comment by adler-j** [comment] 2016-11-24 14:27
I'm able to reproduce this on my windows laptop with the following code:

```python
import odl

# Discrete reconstruction space
discr_reco_space = odl.uniform_discr(0, 1, 100)

# Operator
A = odl.trafos.FourierTransform(discr_reco_space)

# Create data
phantom = odl.phantom.cuboid(A.domain)
rhs = A(phantom)

# Reconstruct
callback = (odl.solvers.CallbackPrintIteration() &
            odl.solvers.CallbackShow())

# THIS FAILS

#partialIter = odl.solvers.util.PrintIterationPartial()
x = discr_reco_space.zero()
odl.solvers.conjugate_gradient_normal(A, x, rhs, niter=1000, callback=callback)

# THESE WORK JUST FINE
#odl.solvers.conjugate_gradient(A.adjoint * A, x, A.adjoint(rhs), niter=1000, callback=callback)
#odl.solvers.landweber(A, x, rhs, niter=1000, omega=0.1, callback=callback)
```

Setup:

Windows 7

`Python 2.7.10 |Anaconda 2.1.0 (64-bit)| (default, Nov  7 2015, 13:18:40) [MSC v.1500 64 bit (AMD64)] on win32`

```
>>> odl.__version__
'0.5.2'
>>> np.__version__
'1.9.3'
```

**Comment by kohr-h** [comment] 2016-11-24 14:58
Weird bug. For me `x` does get changed and looks very much like the correct solution, but the scaling goes totally haywire. Below the result for 10 instead of 1000 iterations:
![10iters](https://cloud.githubusercontent.com/assets/5030250/20602713/bc4a1572-b25e-11e6-847f-de4e16ed0c87.png)

**Comment by adler-j** [comment] 2016-11-24 15:12
Exact same here.

**Comment by adler-j** [comment] 2016-11-24 15:16
Bug also seems very old, I've tried some commits all the way back to 971f2aa2fd078893ff7737f127c5f7a55d99e39d, which was in september, and I get the exact same result.

**Comment by kohr-h** [comment] 2016-11-24 15:21
There could be an issue with the Fourier transform. I just ran `OperatorTest` with it and got significant deviations from expected results. Things become better with `halfcomplex=False` or if `discr_reco_space` is complex, and with growing number of discretization points. But on the other hand, the test functions run in the tests are ill-suited for the Fourier transform since the aliasing error will be large, i.e. we have a poor correspondence to the actual FT. But it could as well be a bug.
What happens if you change the operator?

**Comment by adler-j** [comment] 2016-11-24 15:21
Well the error was first observed with the ray transform, so it still holds. Also tested to hold for the wavelet transform.

**Comment by adler-j** [comment] 2016-11-24 16:08
I suspect that it is actually the operators that are wrong. Perhaps it is the astra scaling change that is causing issues for you guys with `RayTransform` but not me (since I have the old one). See issue #724

Have you even run the odl tests @davlars? `python -c "import odl; odl.test()"`. This is VERY likely the issue.

Other than that, I think some recenty change, probably #547, broke the adjoint of the wavelet transform and possibly that of the fourier transform. 

I opened an issue for the wavelet transform (where I have verified it to be wrong) #733, and also started some work on a fix #734.

Regarding the fourier transform, I've also opened an issue for this (#735), and added some work (#734).

**Comment by davlars** [comment] 2016-11-25 08:33
Sorry for the delayed response... You're right, the `odl.test()` does indeed crash within the ray transform (`/odl/test/tomo/operators/ray_trafo_test.py`, the `assert almost_equal(result_AxAx, result_xAtAx, places=places)` fails). Thought I'd run this but apparently not... Sorry about that.

But do we experience the same error? I don't see a direct scaling issue but rather that I don't get past the first iteration (or that it iterates but without any actual reconstruction update). 

But overall you seem to have isolated the issue, so we at least now what's causing it. Nice job!

**Comment by adler-j** [comment] 2016-11-25 08:57
> But do we experience the same error? I don't see a direct scaling issue but rather that I don't get past the first iteration (or that it iterates but without any actual reconstruction update).

This can very well be due to a bad scaling. The algorithm as is assumes that the adjoint and forward operators are matched exactly, otherwise it fails. The reason the other solves work is that they do not have this assumption.

Anyway, solution for you is to downgrade ASTRA.

**Comment by adler-j** [comment] 2016-11-28 10:19
I'll take the liberty to close this then. The issue has boiled down to two sub-problems: Astra changing their scaling internally, and our transforms having the wrong adjoint.

Followup issues are:

* RayTransform: #724
* WaveletTransform: #733
* FourierTransform: #735

**Closed by adler-j** 2016-11-28 10:19 UTC
Labels: bug, odl solvers
