### ISSUE TITLE
`domain` uniform_discr is not an `NumpyFn` instance?

### ISSUE THREAD

**Issue by cheney0753** [odlgroup/odl#910] opened 2017-02-15 14:32 UTC
Hi, 

I would like to define an `odl.MatVecOperator` using my own numpy matrix `W`, and use it in `uniform_discr` space. 

So if I just use 
```python
Op =  odl.MatVecOperator(W)
x = odl.uniform_discr(0, 1, 100).zero()
g = Op(x)  
```

it returns: 
```python
g = rn(27000).element([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0])
```

which is not in the uniform_discr domain.

If I define
```python
odl.MatVecOperator(W, odl.uniform_discr, odl.uniform_discr)
``` 
it returns:

```
`domain` uniform_discr()  is not an `NumpyFn` instance
```

Is there any other operator to use?

Edit @kohr-h: Formatting improved

**Comment by kohr-h** [comment] 2017-02-15 15:24
> odl.MatVecOperator( W, odl.uniform_discr, odl.uniform_discr )

That will never work as written, but I assume you used two instances of `DiscreteLp` (result of `uniform_discr`) instead of the function only.

Anyway, this is actually something that should work. The reason it doesn't is that we have this inheritance scheme:
```
FnBase-----------------------
   |                        |
DiscretizedSpace          NumpyFn
   |
DiscreteLp
```
so `DiscreteLp` is not an instance of `NumpyFn` and cannot be used directly. However, there's no reason this shouldn't work since `matrix.dot(x)` does work if `x` is a `DiscreteLpElement`.

**Comment by adler-j** [comment] 2017-02-15 22:20
@kohr-h gave a good response on this particular use case, but at a larger scope there is the bigger problem of handling this for n-d tensrs which has been discussed in the tensor branch. When that is solved, this becomes much more simple. We may need to create a new issue on that.

Also, this is a duplicate of #635.

**Closed** 2017-02-16 13:42 UTC
Labels: needs improvement, odl core
