### ISSUE TITLE
Does ConeBeamGeometry support helical geometry with cylindrical detector?

### ISSUE THREAD

**Issue by wangwei-cmd** [odlgroup/odl#1601] opened 2021-04-23 03:01 UTC
I want to create a  helical geometry with cylindrical detector. Here is my code:

reco_space = odl.uniform_discr(min_pt=[-63.5, -63.5, 0], max_pt=[63.5, 63.5, 14], shape=[128, 128, 15], dtype='float32')
angle_partition = odl.uniform_partition(0, 2*360 * np.pi/180, 721)
detector_partition = odl.uniform_partition([-0.4796, -6], [0.4796, 6], [219, 13])
geometry = odl.tomo.ConeBeamGeometry(angle_partition, detector_partition, src_radius=200, det_radius=200,
    det_curvature_radius=(400, None),  pitch=2*2*np.pi)
ray_trafo = odl.tomo.RayTransform(reco_space, geometry, impl='astra_cuda')

But pycharm raises an error:
NotImplementedError: unknown ASTRA geometry type ConeBeamGeometry(
    uniform_partition(0.0, 12.57, 721),
    uniform_partition([-0.4796, -6.    ], [ 0.4796,  6.    ], (219, 13)),
    src_radius=200.0,
    det_radius=200.0,
    pitch=12.566371
)

**Comment by aringh** [comment] 2021-04-23 04:47
Duplicate of #1602

**Closed by aringh** 2021-04-23 04:47 UTC
